import {test,expect,_electron as electron} from '@playwright/test';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
test('Windows native host: two windows, measured send, output close, persisted draft and empty restart',async()=>{
  test.skip(process.platform!=='win32','Windows host verification runs on Windows only.');
  const data=await mkdtemp(path.join(os.tmpdir(),'dj-live-text-electron-'));
  let app;
  try{
    const launch=async()=>{
      app=await electron.launch({args:['.'],env:{...process.env,DJ_LIVE_TEXT_DATA:data}});
      await expect.poll(()=>app.windows().filter(p=>p.url().endsWith('.html')).length).toBe(2);
      const control=app.windows().find(p=>p.url().endsWith('/index.html'));
      const output=app.windows().find(p=>p.url().endsWith('/output.html'));
      await expect(control.locator('#connection')).toContainText('接続中');
      return {control,output};
    };
    let {control,output}=await launch();
    await expect(output.locator('#stage .glyph')).toHaveCount(0);
    await control.locator('#draft').fill('@mode instant\n**Windows確認** 👨‍👩‍👧‍👦');
    await control.locator('#show').click();
    await expect(output.locator('#stage')).toContainText('Windows確認');
    await expect(control.locator('#show')).toBeFocused();
    const draft=control.locator('#draft'),archived='日本語 **履歴**\n末尾 ';
    await draft.fill('');await draft.pressSequentially(archived);
    for(const modifier of ['Control','Shift','Alt','Meta'])await control.keyboard.press(`${modifier}+F2`);
    await expect(draft).toHaveValue(archived);
    await control.keyboard.press('F2');await expect(draft).toHaveValue('');await expect(draft).toBeFocused();
    expect(await draft.evaluate(el=>el.selectionStart)).toBe(0);
    await control.keyboard.press('Control+z');await expect(draft).toHaveValue(archived);
    await control.keyboard.press('Control+y');await expect(draft).toHaveValue('');
    await control.locator('#history summary').click();await expect(control.locator('#history-entries pre')).toHaveText(archived);
    expect(await output.evaluate(()=>window.host.loadHistory())).toMatchObject({ok:false});
    expect(await output.evaluate(()=>window.host.archiveDraft({source:'forbidden',savedAt:new Date().toISOString()}))).toMatchObject({ok:false});
    await control.locator('#history-entries button').focus();await control.keyboard.press('F2');
    await expect(control.locator('#history-entries article')).toHaveCount(1);
    await control.locator('#draft').fill('再起動後の下書き');
    await expect(output.locator('#stage')).toContainText('Windows確認');
    await output.close();await expect(control.locator('#connection')).toContainText('閉じ');
    await control.locator('summary').filter({hasText:'出力と連携'}).click();
    await control.locator('#open-output').click();
    await expect.poll(()=>app.windows().filter(p=>p.url().endsWith('.html')).length).toBe(2);
    output=app.windows().find(p=>p.url().endsWith('/output.html'));
    await expect(output.locator('#stage .glyph')).toHaveCount(0);
    await control.locator('#background').fill('#123456');
    await control.locator('#apply-settings').click();
    await expect(output.locator('body')).toHaveCSS('background-color','rgb(18, 52, 86)');
    await app.close();
    ({control,output}=await launch());
    await expect(output.locator('body')).toHaveCSS('background-color','rgb(18, 52, 86)');
    await expect(control.locator('#draft')).toHaveValue('再起動後の下書き');
    await control.locator('#history summary').click();await expect(control.locator('#history-entries pre')).toHaveText(archived);
    await expect(control.locator('#live')).toHaveAttribute('aria-pressed','false');
    await expect(output.locator('#stage .glyph')).toHaveCount(0);
    // Synthetic Process/229 verifies the renderer path in target Electron, not real IME.
    await control.locator('#draft').fill('@mode instant\nIME消去');await control.locator('#show').click();
    await expect(output.locator('#stage')).toContainText('IME消去');
    await control.locator('#draft').focus();await control.locator('#draft').dispatchEvent('compositionstart');
    await control.locator('#draft').dispatchEvent('keydown',{key:'Process',code:'F2',keyCode:229,isComposing:true});
    await expect(output.locator('#stage')).toContainText('IME消去');
    await control.locator('#draft').dispatchEvent('keydown',{key:'Process',code:'Backspace',keyCode:229,ctrlKey:true,isComposing:true});
    await expect(output.locator('#stage .glyph')).toHaveCount(0);
    await expect(control.locator('#draft')).toHaveValue('@mode instant\nIME消去');
    await expect(control.locator('#history-entries article')).toHaveCount(1);
    await control.locator('#draft').dispatchEvent('compositionend');
    await expect(output.locator('#stage .glyph')).toHaveCount(0);
    await app.close();app=null;
  }finally{if(app)await app.close();await rm(data,{recursive:true,force:true});}
});
